<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msgError</name>
   <tag></tag>
   <elementGuidId>3d10b6d2-8eb9-40b1-a6d0-e3293cefd3fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/form[1]/h3[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[1]/div[1]/div[1]/form[1]/h3[1]</value>
      <webElementGuid>3497737d-6b4f-4c3b-b23a-621ced1cfc30</webElementGuid>
   </webElementProperties>
</WebElementEntity>
